image:
  name: docker/compose:1.25.4
  entrypoint: [""]

services:
  - docker:dind

stages:
  - build


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  stage: build
  before_script:
    - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - export API_IMAGE=$IMAGE:api
    - export NGINX_IMAGE=$IMAGE:nginx
  script:
    - apk add --no-cache bash
    - chmod +x ./setup_env.sh
    - bash ./setup_env.sh
    - cat .env
    - echo $SECRET_KEY

