image:
  name: docker/compose:1.25.4
  entrypoint: [""]

services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

test:
  stage: test
  image: $IMAGE:api
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: users
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner
    DATABASE_TEST_URL: postgres://runner:runner@postgres:5432/users
  script:
    - export SQL_HOST=$DATABASE_TEST_URL
    - export SQL_DATABASE=$POSTGRES_DB
    - export SQL_USER=$POSTGRES_USER
    - export SQL_PASSWORD=$POSTGRES_PASSWORD
    - cd /usr/src/app
    - python3.8 -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - pip install flake8 isort pytest pytest-django
    - export DEBUG=1
    - pytest -p no:warnings
    - flake8 .
    - isort ./*/*.py --check-only
    - export DEBUG=0
    - python manage.py check --deploy --fail-level=WARNING
