image: docker/compose:1.26.0

stages:
  - build

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  API_IMAGE: $IMAGE:api

build:
  stage: build
  services:
    - docker:dind

  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache bash
    - chmod +x ./api/setup_env.sh
    - bash ./api/setup_env.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:api || true
    - docker-compose -f docker-compose.ci.yml build
    - docker push $IMAGE:api