image:
  name: docker/compose:1.26.0
  entrypoint: [""]

stages:
  - build

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  API_IMAGE: $IMAGE:api
  NGINX_IMAGE: $IMAGE:nginx

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache bash
    - chmod +x ./api/setup_env.sh
    - bash ./api/setup_env.sh
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:api || true
    - docker pull $IMAGE:nginx || true
    - docker-compose -f docker-compose.ci.yml build
    - docker push $IMAGE:api
    - docker push $IMAGE:nginx
