image: docker/compose:1.25.4


services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - export API_IMAGE=$IMAGE:api
    - export NGINX_IMAGE=$IMAGE:nginx
    - apk add --no-cache openssh-client bash
    - chmod +x ./setup_env.sh
    - bash ./setup_env.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY"
