version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: $SECRET_KEY
      cache_from:
        - "${API_IMAGE}"
    image: "${API_IMAGE}"
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
