version: '3.7'

services:
  blog-api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
      cache_from:
        - "${API_IMAGE}"
    image: "${API_IMAGE}"
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./api/.env

