version: '3.7'

services:
  api:
    container_name: api
    image: "${API_IMAGE}"
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: "${NGINX_IMAGE}"
    ports:
      - 80:80
    depends_on:
      - api