version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
      cache_from:
        - "${API_IMAGE}"
    image: "${API_IMAGE}"
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 80:80
    depends_on:
      - api
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
      cache_from:
        - "${UI_IMAGE}"
    image: "${UI_IMAGE}"
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - api
      - nginx
